package com.eridiumcorp.bagz.app.models

import androidx.compose.ui.graphics.Color
import com.eridiumcorp.bagz.app.extensions.extractMap
import com.eridiumcorp.bagz.app.utils.currentMonthActivityKey

data class Activity(
    val activityData: List<ActivitySummary>?,
) {
    companion object {
        fun fromMap(map: Map<String, Any?>): Activity {
            val currentActivityKey = currentMonthActivityKey()
            println("123456789: Current activity key: $currentActivityKey")
            val currentActivity = map.extractMap(currentActivityKey)
            if (currentActivity == null) {
                return Activity(null)
            }
            val activitySummaryList = currentActivity
                .entries.mapNotNull { entry ->
                    ActivitySummary.fromEntry(entry)
                }.sortedByDescending { it.amount }
            return Activity(activitySummaryList)
        }
    }
}

data class ActivitySummary(val type: ActivityType, val amount: Double) {

    companion object {
        fun fromEntry(entry: Map.Entry<String, Any?>): ActivitySummary? {
            val amount = when (entry.value) {
                is Double -> entry.value as Double
                is Int -> (entry.value as Int).toDouble()
                is Float -> (entry.value as Float).toDouble()
                else -> null
            }
            if (amount != null && amount >= 1) {
                val activityType = ActivityType.fromString(entry.key)
                if (activityType != null) {
                    return ActivitySummary(activityType, kotlin.math.abs(amount))
                }
            }
            return null
        }
    }
}

enum class ActivityType(val color: Color) {
    INCOME(Color(0xFF00C853)),
    INCOME_DIVIDENDS(INCOME.color),
    INCOME_INTEREST_EARNED(INCOME.color),
    INCOME_RETIREMENT_PENSION(INCOME.color),
    INCOME_TAX_REFUND(INCOME.color),
    INCOME_UNEMPLOYMENT(INCOME.color),
    INCOME_WAGES(INCOME.color),
    INCOME_OTHER_INCOME(INCOME.color),

    TRANSFER_IN(Color(0xFF00B0FF)),
    TRANSFER_IN_CASH_ADVANCES_AND_LOANS(TRANSFER_IN.color),
    TRANSFER_IN_DEPOSIT(TRANSFER_IN.color),
    TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS(TRANSFER_IN.color),
    TRANSFER_IN_SAVINGS(TRANSFER_IN.color),
    TRANSFER_IN_ACCOUNT_TRANSFER(TRANSFER_IN.color),
    TRANSFER_IN_OTHER_TRANSFER_IN(TRANSFER_IN.color),

    TRANSFER_OUT(Color(0xFFD50000)), // Using a distinct color for TRANSFER_OUT
    TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS(TRANSFER_OUT.color),
    TRANSFER_OUT_SAVINGS(TRANSFER_OUT.color),
    TRANSFER_OUT_WITHDRAWAL(TRANSFER_OUT.color),
    TRANSFER_OUT_ACCOUNT_TRANSFER(TRANSFER_OUT.color),
    TRANSFER_OUT_OTHER_TRANSFER_OUT(TRANSFER_OUT.color),

    LOAN_PAYMENTS(Color(0xFFFFD600)),
    LOAN_PAYMENTS_CAR_PAYMENT(LOAN_PAYMENTS.color),
    LOAN_PAYMENTS_CREDIT_CARD_PAYMENT(LOAN_PAYMENTS.color),
    LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT(LOAN_PAYMENTS.color),
    LOAN_PAYMENTS_MORTGAGE_PAYMENT(LOAN_PAYMENTS.color),
    LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT(LOAN_PAYMENTS.color),
    LOAN_PAYMENTS_OTHER_PAYMENT(LOAN_PAYMENTS.color),

    BANK_FEES(Color(0xFFD50000)),
    BANK_FEES_ATM_FEES(BANK_FEES.color),
    BANK_FEES_FOREIGN_TRANSACTION_FEES(BANK_FEES.color),
    BANK_FEES_INSUFFICIENT_FUNDS(BANK_FEES.color),
    BANK_FEES_INTEREST_CHARGE(BANK_FEES.color),
    BANK_FEES_OVERDRAFT_FEES(BANK_FEES.color),
    BANK_FEES_OTHER_BANK_FEES(BANK_FEES.color),

    ENTERTAINMENT(Color(0xFFAA00FF)),
    ENTERTAINMENT_CASINOS_AND_GAMBLING(ENTERTAINMENT.color),
    ENTERTAINMENT_MUSIC_AND_AUDIO(ENTERTAINMENT.color),
    ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS(ENTERTAINMENT.color),
    ENTERTAINMENT_TV_AND_MOVIES(ENTERTAINMENT.color),
    ENTERTAINMENT_VIDEO_GAMES(ENTERTAINMENT.color),
    ENTERTAINMENT_OTHER_ENTERTAINMENT(ENTERTAINMENT.color),

    FOOD_AND_DRINK(Color(0xFF00BCD4)),
    FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR(FOOD_AND_DRINK.color),
    FOOD_AND_DRINK_COFFEE(FOOD_AND_DRINK.color),
    FOOD_AND_DRINK_FAST_FOOD(FOOD_AND_DRINK.color),
    FOOD_AND_DRINK_GROCERIES(FOOD_AND_DRINK.color),
    FOOD_AND_DRINK_RESTAURANT(FOOD_AND_DRINK.color),
    FOOD_AND_DRINK_VENDING_MACHINES(FOOD_AND_DRINK.color),
    FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK(FOOD_AND_DRINK.color),

    GENERAL_MERCHANDISE(Color(0xFF64B5F6)),
    GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS(GENERAL_MERCHANDISE.color),
    GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES(GENERAL_MERCHANDISE.color),
    GENERAL_MERCHANDISE_CONVENIENCE_STORES(GENERAL_MERCHANDISE.color),
    GENERAL_MERCHANDISE_DEPARTMENT_STORES(GENERAL_MERCHANDISE.color),
    GENERAL_MERCHANDISE_DISCOUNT_STORES(GENERAL_MERCHANDISE.color),
    GENERAL_MERCHANDISE_ELECTRONICS(GENERAL_MERCHANDISE.color),
    GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES(GENERAL_MERCHANDISE.color),
    GENERAL_MERCHANDISE_OFFICE_SUPPLIES(GENERAL_MERCHANDISE.color),
    GENERAL_MERCHANDISE_ONLINE_MARKETPLACES(GENERAL_MERCHANDISE.color),
    GENERAL_MERCHANDISE_PET_SUPPLIES(GENERAL_MERCHANDISE.color),
    GENERAL_MERCHANDISE_SPORTING_GOODS(GENERAL_MERCHANDISE.color),
    GENERAL_MERCHANDISE_SUPERSTORES(GENERAL_MERCHANDISE.color),
    GENERAL_MERCHANDISE_TOBACCO_AND_VAPE(GENERAL_MERCHANDISE.color),
    GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE(GENERAL_MERCHANDISE.color),

    HOME_IMPROVEMENT(Color(0xFFFF9800)),
    HOME_IMPROVEMENT_FURNITURE(HOME_IMPROVEMENT.color),
    HOME_IMPROVEMENT_HARDWARE(HOME_IMPROVEMENT.color),
    HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE(HOME_IMPROVEMENT.color),
    HOME_IMPROVEMENT_SECURITY(HOME_IMPROVEMENT.color),
    HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT(HOME_IMPROVEMENT.color),

    MEDICAL(Color(0xFFE91E63)),
    MEDICAL_DENTAL_CARE(MEDICAL.color),
    MEDICAL_EYE_CARE(MEDICAL.color),
    MEDICAL_NURSING_CARE(MEDICAL.color),
    MEDICAL_PHARMACIES_AND_SUPPLEMENTS(MEDICAL.color),
    MEDICAL_PRIMARY_CARE(MEDICAL.color),
    MEDICAL_VETERINARY_SERVICES(MEDICAL.color),
    MEDICAL_OTHER_MEDICAL(MEDICAL.color),

    PERSONAL_CARE(Color(0xFF9C27B0)),
    PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS(PERSONAL_CARE.color),
    PERSONAL_CARE_HAIR_AND_BEAUTY(PERSONAL_CARE.color),
    PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING(PERSONAL_CARE.color),
    PERSONAL_CARE_OTHER_PERSONAL_CARE(PERSONAL_CARE.color),

    GENERAL_SERVICES(Color(0xFF009688)),
    GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING(GENERAL_SERVICES.color),
    GENERAL_SERVICES_AUTOMOTIVE(GENERAL_SERVICES.color),
    GENERAL_SERVICES_CHILDCARE(GENERAL_SERVICES.color),
    GENERAL_SERVICES_CONSULTING_AND_LEGAL(GENERAL_SERVICES.color),
    GENERAL_SERVICES_EDUCATION(GENERAL_SERVICES.color),
    GENERAL_SERVICES_INSURANCE(GENERAL_SERVICES.color),
    GENERAL_SERVICES_POSTAGE_AND_SHIPPING(GENERAL_SERVICES.color),
    GENERAL_SERVICES_STORAGE(GENERAL_SERVICES.color),
    GENERAL_SERVICES_OTHER_GENERAL_SERVICES(GENERAL_SERVICES.color),

    GOVERNMENT_AND_NON_PROFIT(Color(0xFFF44336)),
    GOVERNMENT_AND_NON_PROFIT_DONATIONS(GOVERNMENT_AND_NON_PROFIT.color),
    GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES(GOVERNMENT_AND_NON_PROFIT.color),
    GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT(GOVERNMENT_AND_NON_PROFIT.color),
    GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT(GOVERNMENT_AND_NON_PROFIT.color),

    TRANSPORTATION(Color(0xFF2196F3)),
    TRANSPORTATION_BIKES_AND_SCOOTERS(TRANSPORTATION.color),
    TRANSPORTATION_GAS(TRANSPORTATION.color),
    TRANSPORTATION_PARKING(TRANSPORTATION.color),
    TRANSPORTATION_PUBLIC_TRANSIT(TRANSPORTATION.color),
    TRANSPORTATION_TAXIS_AND_RIDE_SHARES(TRANSPORTATION.color),
    TRANSPORTATION_TOLLS(TRANSPORTATION.color),
    TRANSPORTATION_OTHER_TRANSPORTATION(TRANSPORTATION.color),

    TRAVEL(Color(0xFF4CAF50)),
    TRAVEL_FLIGHTS(TRAVEL.color),
    TRAVEL_LODGING(TRAVEL.color),
    TRAVEL_RENTAL_CARS(TRAVEL.color),
    TRAVEL_OTHER_TRAVEL(TRAVEL.color),

    RENT_AND_UTILITIES(Color(0xFFFFC107)),
    RENT_AND_UTILITIES_GAS_AND_ELECTRICITY(RENT_AND_UTILITIES.color),
    RENT_AND_UTILITIES_INTERNET_AND_CABLE(RENT_AND_UTILITIES.color),
    RENT_AND_UTILITIES_RENT(RENT_AND_UTILITIES.color),
    RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT(RENT_AND_UTILITIES.color),
    RENT_AND_UTILITIES_TELEPHONE(RENT_AND_UTILITIES.color),
    RENT_AND_UTILITIES_WATER(RENT_AND_UTILITIES.color),
    RENT_AND_UTILITIES_OTHER_UTILITIES(RENT_AND_UTILITIES.color);

    companion object {
        fun fromString(type: String): ActivityType? {
            return entries.find { it.name == type }
        }
    }
}
